// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AppListResponse.proto

package com.netty.client.innermsg;

public final class AppListResponseProto {
  private AppListResponseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AppListResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AppListResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string messageId = 1;</code>
     *
     * <pre>
     *消息id
     * </pre>
     */
    boolean hasMessageId();
    /**
     * <code>required string messageId = 1;</code>
     *
     * <pre>
     *消息id
     * </pre>
     */
    java.lang.String getMessageId();
    /**
     * <code>required string messageId = 1;</code>
     *
     * <pre>
     *消息id
     * </pre>
     */
    com.google.protobuf.ByteString
        getMessageIdBytes();

    /**
     * <code>required int32 code = 2;</code>
     *
     * <pre>
     *返回码，200表示正确
     * </pre>
     */
    boolean hasCode();
    /**
     * <code>required int32 code = 2;</code>
     *
     * <pre>
     *返回码，200表示正确
     * </pre>
     */
    int getCode();

    /**
     * <code>repeated .AppInfo list = 3;</code>
     */
    java.util.List<com.netty.client.innermsg.AppListResponseProto.AppInfo> 
        getListList();
    /**
     * <code>repeated .AppInfo list = 3;</code>
     */
    com.netty.client.innermsg.AppListResponseProto.AppInfo getList(int index);
    /**
     * <code>repeated .AppInfo list = 3;</code>
     */
    int getListCount();
    /**
     * <code>repeated .AppInfo list = 3;</code>
     */
    java.util.List<? extends com.netty.client.innermsg.AppListResponseProto.AppInfoOrBuilder> 
        getListOrBuilderList();
    /**
     * <code>repeated .AppInfo list = 3;</code>
     */
    com.netty.client.innermsg.AppListResponseProto.AppInfoOrBuilder getListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code AppListResponse}
   */
  public static final class AppListResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:AppListResponse)
      AppListResponseOrBuilder {
    // Use AppListResponse.newBuilder() to construct.
    private AppListResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AppListResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AppListResponse defaultInstance;
    public static AppListResponse getDefaultInstance() {
      return defaultInstance;
    }

    public AppListResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AppListResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              messageId_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              code_ = input.readInt32();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                list_ = new java.util.ArrayList<com.netty.client.innermsg.AppListResponseProto.AppInfo>();
                mutable_bitField0_ |= 0x00000004;
              }
              list_.add(input.readMessage(com.netty.client.innermsg.AppListResponseProto.AppInfo.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          list_ = java.util.Collections.unmodifiableList(list_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.netty.client.innermsg.AppListResponseProto.internal_static_AppListResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.netty.client.innermsg.AppListResponseProto.internal_static_AppListResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.netty.client.innermsg.AppListResponseProto.AppListResponse.class, com.netty.client.innermsg.AppListResponseProto.AppListResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<AppListResponse> PARSER =
        new com.google.protobuf.AbstractParser<AppListResponse>() {
      public AppListResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AppListResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AppListResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int MESSAGEID_FIELD_NUMBER = 1;
    private java.lang.Object messageId_;
    /**
     * <code>required string messageId = 1;</code>
     *
     * <pre>
     *消息id
     * </pre>
     */
    public boolean hasMessageId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string messageId = 1;</code>
     *
     * <pre>
     *消息id
     * </pre>
     */
    public java.lang.String getMessageId() {
      java.lang.Object ref = messageId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          messageId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string messageId = 1;</code>
     *
     * <pre>
     *消息id
     * </pre>
     */
    public com.google.protobuf.ByteString
        getMessageIdBytes() {
      java.lang.Object ref = messageId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CODE_FIELD_NUMBER = 2;
    private int code_;
    /**
     * <code>required int32 code = 2;</code>
     *
     * <pre>
     *返回码，200表示正确
     * </pre>
     */
    public boolean hasCode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 code = 2;</code>
     *
     * <pre>
     *返回码，200表示正确
     * </pre>
     */
    public int getCode() {
      return code_;
    }

    public static final int LIST_FIELD_NUMBER = 3;
    private java.util.List<com.netty.client.innermsg.AppListResponseProto.AppInfo> list_;
    /**
     * <code>repeated .AppInfo list = 3;</code>
     */
    public java.util.List<com.netty.client.innermsg.AppListResponseProto.AppInfo> getListList() {
      return list_;
    }
    /**
     * <code>repeated .AppInfo list = 3;</code>
     */
    public java.util.List<? extends com.netty.client.innermsg.AppListResponseProto.AppInfoOrBuilder> 
        getListOrBuilderList() {
      return list_;
    }
    /**
     * <code>repeated .AppInfo list = 3;</code>
     */
    public int getListCount() {
      return list_.size();
    }
    /**
     * <code>repeated .AppInfo list = 3;</code>
     */
    public com.netty.client.innermsg.AppListResponseProto.AppInfo getList(int index) {
      return list_.get(index);
    }
    /**
     * <code>repeated .AppInfo list = 3;</code>
     */
    public com.netty.client.innermsg.AppListResponseProto.AppInfoOrBuilder getListOrBuilder(
        int index) {
      return list_.get(index);
    }

    private void initFields() {
      messageId_ = "";
      code_ = 0;
      list_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasMessageId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getListCount(); i++) {
        if (!getList(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getMessageIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, code_);
      }
      for (int i = 0; i < list_.size(); i++) {
        output.writeMessage(3, list_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getMessageIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, code_);
      }
      for (int i = 0; i < list_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, list_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.netty.client.innermsg.AppListResponseProto.AppListResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netty.client.innermsg.AppListResponseProto.AppListResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netty.client.innermsg.AppListResponseProto.AppListResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netty.client.innermsg.AppListResponseProto.AppListResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netty.client.innermsg.AppListResponseProto.AppListResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.netty.client.innermsg.AppListResponseProto.AppListResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.netty.client.innermsg.AppListResponseProto.AppListResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.netty.client.innermsg.AppListResponseProto.AppListResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.netty.client.innermsg.AppListResponseProto.AppListResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.netty.client.innermsg.AppListResponseProto.AppListResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.netty.client.innermsg.AppListResponseProto.AppListResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AppListResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AppListResponse)
        com.netty.client.innermsg.AppListResponseProto.AppListResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.netty.client.innermsg.AppListResponseProto.internal_static_AppListResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.netty.client.innermsg.AppListResponseProto.internal_static_AppListResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.netty.client.innermsg.AppListResponseProto.AppListResponse.class, com.netty.client.innermsg.AppListResponseProto.AppListResponse.Builder.class);
      }

      // Construct using com.netty.client.innermsg.AppListResponseProto.AppListResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getListFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        messageId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        code_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (listBuilder_ == null) {
          list_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          listBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.netty.client.innermsg.AppListResponseProto.internal_static_AppListResponse_descriptor;
      }

      public com.netty.client.innermsg.AppListResponseProto.AppListResponse getDefaultInstanceForType() {
        return com.netty.client.innermsg.AppListResponseProto.AppListResponse.getDefaultInstance();
      }

      public com.netty.client.innermsg.AppListResponseProto.AppListResponse build() {
        com.netty.client.innermsg.AppListResponseProto.AppListResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.netty.client.innermsg.AppListResponseProto.AppListResponse buildPartial() {
        com.netty.client.innermsg.AppListResponseProto.AppListResponse result = new com.netty.client.innermsg.AppListResponseProto.AppListResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.messageId_ = messageId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.code_ = code_;
        if (listBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            list_ = java.util.Collections.unmodifiableList(list_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.list_ = list_;
        } else {
          result.list_ = listBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.netty.client.innermsg.AppListResponseProto.AppListResponse) {
          return mergeFrom((com.netty.client.innermsg.AppListResponseProto.AppListResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.netty.client.innermsg.AppListResponseProto.AppListResponse other) {
        if (other == com.netty.client.innermsg.AppListResponseProto.AppListResponse.getDefaultInstance()) return this;
        if (other.hasMessageId()) {
          bitField0_ |= 0x00000001;
          messageId_ = other.messageId_;
          onChanged();
        }
        if (other.hasCode()) {
          setCode(other.getCode());
        }
        if (listBuilder_ == null) {
          if (!other.list_.isEmpty()) {
            if (list_.isEmpty()) {
              list_ = other.list_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureListIsMutable();
              list_.addAll(other.list_);
            }
            onChanged();
          }
        } else {
          if (!other.list_.isEmpty()) {
            if (listBuilder_.isEmpty()) {
              listBuilder_.dispose();
              listBuilder_ = null;
              list_ = other.list_;
              bitField0_ = (bitField0_ & ~0x00000004);
              listBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getListFieldBuilder() : null;
            } else {
              listBuilder_.addAllMessages(other.list_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMessageId()) {
          
          return false;
        }
        if (!hasCode()) {
          
          return false;
        }
        for (int i = 0; i < getListCount(); i++) {
          if (!getList(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.netty.client.innermsg.AppListResponseProto.AppListResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.netty.client.innermsg.AppListResponseProto.AppListResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object messageId_ = "";
      /**
       * <code>required string messageId = 1;</code>
       *
       * <pre>
       *消息id
       * </pre>
       */
      public boolean hasMessageId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string messageId = 1;</code>
       *
       * <pre>
       *消息id
       * </pre>
       */
      public java.lang.String getMessageId() {
        java.lang.Object ref = messageId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            messageId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string messageId = 1;</code>
       *
       * <pre>
       *消息id
       * </pre>
       */
      public com.google.protobuf.ByteString
          getMessageIdBytes() {
        java.lang.Object ref = messageId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          messageId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string messageId = 1;</code>
       *
       * <pre>
       *消息id
       * </pre>
       */
      public Builder setMessageId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        messageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string messageId = 1;</code>
       *
       * <pre>
       *消息id
       * </pre>
       */
      public Builder clearMessageId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        messageId_ = getDefaultInstance().getMessageId();
        onChanged();
        return this;
      }
      /**
       * <code>required string messageId = 1;</code>
       *
       * <pre>
       *消息id
       * </pre>
       */
      public Builder setMessageIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        messageId_ = value;
        onChanged();
        return this;
      }

      private int code_ ;
      /**
       * <code>required int32 code = 2;</code>
       *
       * <pre>
       *返回码，200表示正确
       * </pre>
       */
      public boolean hasCode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 code = 2;</code>
       *
       * <pre>
       *返回码，200表示正确
       * </pre>
       */
      public int getCode() {
        return code_;
      }
      /**
       * <code>required int32 code = 2;</code>
       *
       * <pre>
       *返回码，200表示正确
       * </pre>
       */
      public Builder setCode(int value) {
        bitField0_ |= 0x00000002;
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 code = 2;</code>
       *
       * <pre>
       *返回码，200表示正确
       * </pre>
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        code_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.netty.client.innermsg.AppListResponseProto.AppInfo> list_ =
        java.util.Collections.emptyList();
      private void ensureListIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          list_ = new java.util.ArrayList<com.netty.client.innermsg.AppListResponseProto.AppInfo>(list_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.netty.client.innermsg.AppListResponseProto.AppInfo, com.netty.client.innermsg.AppListResponseProto.AppInfo.Builder, com.netty.client.innermsg.AppListResponseProto.AppInfoOrBuilder> listBuilder_;

      /**
       * <code>repeated .AppInfo list = 3;</code>
       */
      public java.util.List<com.netty.client.innermsg.AppListResponseProto.AppInfo> getListList() {
        if (listBuilder_ == null) {
          return java.util.Collections.unmodifiableList(list_);
        } else {
          return listBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .AppInfo list = 3;</code>
       */
      public int getListCount() {
        if (listBuilder_ == null) {
          return list_.size();
        } else {
          return listBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .AppInfo list = 3;</code>
       */
      public com.netty.client.innermsg.AppListResponseProto.AppInfo getList(int index) {
        if (listBuilder_ == null) {
          return list_.get(index);
        } else {
          return listBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .AppInfo list = 3;</code>
       */
      public Builder setList(
          int index, com.netty.client.innermsg.AppListResponseProto.AppInfo value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.set(index, value);
          onChanged();
        } else {
          listBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .AppInfo list = 3;</code>
       */
      public Builder setList(
          int index, com.netty.client.innermsg.AppListResponseProto.AppInfo.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.set(index, builderForValue.build());
          onChanged();
        } else {
          listBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .AppInfo list = 3;</code>
       */
      public Builder addList(com.netty.client.innermsg.AppListResponseProto.AppInfo value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.add(value);
          onChanged();
        } else {
          listBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .AppInfo list = 3;</code>
       */
      public Builder addList(
          int index, com.netty.client.innermsg.AppListResponseProto.AppInfo value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.add(index, value);
          onChanged();
        } else {
          listBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .AppInfo list = 3;</code>
       */
      public Builder addList(
          com.netty.client.innermsg.AppListResponseProto.AppInfo.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.add(builderForValue.build());
          onChanged();
        } else {
          listBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .AppInfo list = 3;</code>
       */
      public Builder addList(
          int index, com.netty.client.innermsg.AppListResponseProto.AppInfo.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.add(index, builderForValue.build());
          onChanged();
        } else {
          listBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .AppInfo list = 3;</code>
       */
      public Builder addAllList(
          java.lang.Iterable<? extends com.netty.client.innermsg.AppListResponseProto.AppInfo> values) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, list_);
          onChanged();
        } else {
          listBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .AppInfo list = 3;</code>
       */
      public Builder clearList() {
        if (listBuilder_ == null) {
          list_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          listBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .AppInfo list = 3;</code>
       */
      public Builder removeList(int index) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.remove(index);
          onChanged();
        } else {
          listBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .AppInfo list = 3;</code>
       */
      public com.netty.client.innermsg.AppListResponseProto.AppInfo.Builder getListBuilder(
          int index) {
        return getListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .AppInfo list = 3;</code>
       */
      public com.netty.client.innermsg.AppListResponseProto.AppInfoOrBuilder getListOrBuilder(
          int index) {
        if (listBuilder_ == null) {
          return list_.get(index);  } else {
          return listBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .AppInfo list = 3;</code>
       */
      public java.util.List<? extends com.netty.client.innermsg.AppListResponseProto.AppInfoOrBuilder> 
           getListOrBuilderList() {
        if (listBuilder_ != null) {
          return listBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(list_);
        }
      }
      /**
       * <code>repeated .AppInfo list = 3;</code>
       */
      public com.netty.client.innermsg.AppListResponseProto.AppInfo.Builder addListBuilder() {
        return getListFieldBuilder().addBuilder(
            com.netty.client.innermsg.AppListResponseProto.AppInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .AppInfo list = 3;</code>
       */
      public com.netty.client.innermsg.AppListResponseProto.AppInfo.Builder addListBuilder(
          int index) {
        return getListFieldBuilder().addBuilder(
            index, com.netty.client.innermsg.AppListResponseProto.AppInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .AppInfo list = 3;</code>
       */
      public java.util.List<com.netty.client.innermsg.AppListResponseProto.AppInfo.Builder> 
           getListBuilderList() {
        return getListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.netty.client.innermsg.AppListResponseProto.AppInfo, com.netty.client.innermsg.AppListResponseProto.AppInfo.Builder, com.netty.client.innermsg.AppListResponseProto.AppInfoOrBuilder> 
          getListFieldBuilder() {
        if (listBuilder_ == null) {
          listBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.netty.client.innermsg.AppListResponseProto.AppInfo, com.netty.client.innermsg.AppListResponseProto.AppInfo.Builder, com.netty.client.innermsg.AppListResponseProto.AppInfoOrBuilder>(
                  list_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          list_ = null;
        }
        return listBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:AppListResponse)
    }

    static {
      defaultInstance = new AppListResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:AppListResponse)
  }

  public interface AppInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AppInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string packageName = 1;</code>
     */
    boolean hasPackageName();
    /**
     * <code>required string packageName = 1;</code>
     */
    java.lang.String getPackageName();
    /**
     * <code>required string packageName = 1;</code>
     */
    com.google.protobuf.ByteString
        getPackageNameBytes();

    /**
     * <code>required string appName = 2;</code>
     */
    boolean hasAppName();
    /**
     * <code>required string appName = 2;</code>
     */
    java.lang.String getAppName();
    /**
     * <code>required string appName = 2;</code>
     */
    com.google.protobuf.ByteString
        getAppNameBytes();

    /**
     * <code>required int32 versionCode = 3;</code>
     */
    boolean hasVersionCode();
    /**
     * <code>required int32 versionCode = 3;</code>
     */
    int getVersionCode();

    /**
     * <code>required string versionName = 4;</code>
     */
    boolean hasVersionName();
    /**
     * <code>required string versionName = 4;</code>
     */
    java.lang.String getVersionName();
    /**
     * <code>required string versionName = 4;</code>
     */
    com.google.protobuf.ByteString
        getVersionNameBytes();

    /**
     * <code>required bool isSystem = 5;</code>
     */
    boolean hasIsSystem();
    /**
     * <code>required bool isSystem = 5;</code>
     */
    boolean getIsSystem();
  }
  /**
   * Protobuf type {@code AppInfo}
   */
  public static final class AppInfo extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:AppInfo)
      AppInfoOrBuilder {
    // Use AppInfo.newBuilder() to construct.
    private AppInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AppInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AppInfo defaultInstance;
    public static AppInfo getDefaultInstance() {
      return defaultInstance;
    }

    public AppInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AppInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              packageName_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              appName_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              versionCode_ = input.readInt32();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              versionName_ = bs;
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              isSystem_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.netty.client.innermsg.AppListResponseProto.internal_static_AppInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.netty.client.innermsg.AppListResponseProto.internal_static_AppInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.netty.client.innermsg.AppListResponseProto.AppInfo.class, com.netty.client.innermsg.AppListResponseProto.AppInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<AppInfo> PARSER =
        new com.google.protobuf.AbstractParser<AppInfo>() {
      public AppInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AppInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AppInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int PACKAGENAME_FIELD_NUMBER = 1;
    private java.lang.Object packageName_;
    /**
     * <code>required string packageName = 1;</code>
     */
    public boolean hasPackageName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string packageName = 1;</code>
     */
    public java.lang.String getPackageName() {
      java.lang.Object ref = packageName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          packageName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string packageName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPackageNameBytes() {
      java.lang.Object ref = packageName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        packageName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int APPNAME_FIELD_NUMBER = 2;
    private java.lang.Object appName_;
    /**
     * <code>required string appName = 2;</code>
     */
    public boolean hasAppName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string appName = 2;</code>
     */
    public java.lang.String getAppName() {
      java.lang.Object ref = appName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          appName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string appName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAppNameBytes() {
      java.lang.Object ref = appName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VERSIONCODE_FIELD_NUMBER = 3;
    private int versionCode_;
    /**
     * <code>required int32 versionCode = 3;</code>
     */
    public boolean hasVersionCode() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 versionCode = 3;</code>
     */
    public int getVersionCode() {
      return versionCode_;
    }

    public static final int VERSIONNAME_FIELD_NUMBER = 4;
    private java.lang.Object versionName_;
    /**
     * <code>required string versionName = 4;</code>
     */
    public boolean hasVersionName() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string versionName = 4;</code>
     */
    public java.lang.String getVersionName() {
      java.lang.Object ref = versionName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          versionName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string versionName = 4;</code>
     */
    public com.google.protobuf.ByteString
        getVersionNameBytes() {
      java.lang.Object ref = versionName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        versionName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ISSYSTEM_FIELD_NUMBER = 5;
    private boolean isSystem_;
    /**
     * <code>required bool isSystem = 5;</code>
     */
    public boolean hasIsSystem() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required bool isSystem = 5;</code>
     */
    public boolean getIsSystem() {
      return isSystem_;
    }

    private void initFields() {
      packageName_ = "";
      appName_ = "";
      versionCode_ = 0;
      versionName_ = "";
      isSystem_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasPackageName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAppName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasVersionCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasVersionName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIsSystem()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getPackageNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getAppNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, versionCode_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getVersionNameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBool(5, isSystem_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getPackageNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getAppNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, versionCode_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getVersionNameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, isSystem_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.netty.client.innermsg.AppListResponseProto.AppInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netty.client.innermsg.AppListResponseProto.AppInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netty.client.innermsg.AppListResponseProto.AppInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netty.client.innermsg.AppListResponseProto.AppInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netty.client.innermsg.AppListResponseProto.AppInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.netty.client.innermsg.AppListResponseProto.AppInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.netty.client.innermsg.AppListResponseProto.AppInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.netty.client.innermsg.AppListResponseProto.AppInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.netty.client.innermsg.AppListResponseProto.AppInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.netty.client.innermsg.AppListResponseProto.AppInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.netty.client.innermsg.AppListResponseProto.AppInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AppInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AppInfo)
        com.netty.client.innermsg.AppListResponseProto.AppInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.netty.client.innermsg.AppListResponseProto.internal_static_AppInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.netty.client.innermsg.AppListResponseProto.internal_static_AppInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.netty.client.innermsg.AppListResponseProto.AppInfo.class, com.netty.client.innermsg.AppListResponseProto.AppInfo.Builder.class);
      }

      // Construct using com.netty.client.innermsg.AppListResponseProto.AppInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        packageName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        appName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        versionCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        versionName_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        isSystem_ = false;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.netty.client.innermsg.AppListResponseProto.internal_static_AppInfo_descriptor;
      }

      public com.netty.client.innermsg.AppListResponseProto.AppInfo getDefaultInstanceForType() {
        return com.netty.client.innermsg.AppListResponseProto.AppInfo.getDefaultInstance();
      }

      public com.netty.client.innermsg.AppListResponseProto.AppInfo build() {
        com.netty.client.innermsg.AppListResponseProto.AppInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.netty.client.innermsg.AppListResponseProto.AppInfo buildPartial() {
        com.netty.client.innermsg.AppListResponseProto.AppInfo result = new com.netty.client.innermsg.AppListResponseProto.AppInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.packageName_ = packageName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.appName_ = appName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.versionCode_ = versionCode_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.versionName_ = versionName_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.isSystem_ = isSystem_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.netty.client.innermsg.AppListResponseProto.AppInfo) {
          return mergeFrom((com.netty.client.innermsg.AppListResponseProto.AppInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.netty.client.innermsg.AppListResponseProto.AppInfo other) {
        if (other == com.netty.client.innermsg.AppListResponseProto.AppInfo.getDefaultInstance()) return this;
        if (other.hasPackageName()) {
          bitField0_ |= 0x00000001;
          packageName_ = other.packageName_;
          onChanged();
        }
        if (other.hasAppName()) {
          bitField0_ |= 0x00000002;
          appName_ = other.appName_;
          onChanged();
        }
        if (other.hasVersionCode()) {
          setVersionCode(other.getVersionCode());
        }
        if (other.hasVersionName()) {
          bitField0_ |= 0x00000008;
          versionName_ = other.versionName_;
          onChanged();
        }
        if (other.hasIsSystem()) {
          setIsSystem(other.getIsSystem());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPackageName()) {
          
          return false;
        }
        if (!hasAppName()) {
          
          return false;
        }
        if (!hasVersionCode()) {
          
          return false;
        }
        if (!hasVersionName()) {
          
          return false;
        }
        if (!hasIsSystem()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.netty.client.innermsg.AppListResponseProto.AppInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.netty.client.innermsg.AppListResponseProto.AppInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object packageName_ = "";
      /**
       * <code>required string packageName = 1;</code>
       */
      public boolean hasPackageName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string packageName = 1;</code>
       */
      public java.lang.String getPackageName() {
        java.lang.Object ref = packageName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            packageName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string packageName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getPackageNameBytes() {
        java.lang.Object ref = packageName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          packageName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string packageName = 1;</code>
       */
      public Builder setPackageName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        packageName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string packageName = 1;</code>
       */
      public Builder clearPackageName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        packageName_ = getDefaultInstance().getPackageName();
        onChanged();
        return this;
      }
      /**
       * <code>required string packageName = 1;</code>
       */
      public Builder setPackageNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        packageName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object appName_ = "";
      /**
       * <code>required string appName = 2;</code>
       */
      public boolean hasAppName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string appName = 2;</code>
       */
      public java.lang.String getAppName() {
        java.lang.Object ref = appName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            appName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string appName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAppNameBytes() {
        java.lang.Object ref = appName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          appName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string appName = 2;</code>
       */
      public Builder setAppName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        appName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string appName = 2;</code>
       */
      public Builder clearAppName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        appName_ = getDefaultInstance().getAppName();
        onChanged();
        return this;
      }
      /**
       * <code>required string appName = 2;</code>
       */
      public Builder setAppNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        appName_ = value;
        onChanged();
        return this;
      }

      private int versionCode_ ;
      /**
       * <code>required int32 versionCode = 3;</code>
       */
      public boolean hasVersionCode() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 versionCode = 3;</code>
       */
      public int getVersionCode() {
        return versionCode_;
      }
      /**
       * <code>required int32 versionCode = 3;</code>
       */
      public Builder setVersionCode(int value) {
        bitField0_ |= 0x00000004;
        versionCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 versionCode = 3;</code>
       */
      public Builder clearVersionCode() {
        bitField0_ = (bitField0_ & ~0x00000004);
        versionCode_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object versionName_ = "";
      /**
       * <code>required string versionName = 4;</code>
       */
      public boolean hasVersionName() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string versionName = 4;</code>
       */
      public java.lang.String getVersionName() {
        java.lang.Object ref = versionName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            versionName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string versionName = 4;</code>
       */
      public com.google.protobuf.ByteString
          getVersionNameBytes() {
        java.lang.Object ref = versionName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          versionName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string versionName = 4;</code>
       */
      public Builder setVersionName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        versionName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string versionName = 4;</code>
       */
      public Builder clearVersionName() {
        bitField0_ = (bitField0_ & ~0x00000008);
        versionName_ = getDefaultInstance().getVersionName();
        onChanged();
        return this;
      }
      /**
       * <code>required string versionName = 4;</code>
       */
      public Builder setVersionNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        versionName_ = value;
        onChanged();
        return this;
      }

      private boolean isSystem_ ;
      /**
       * <code>required bool isSystem = 5;</code>
       */
      public boolean hasIsSystem() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required bool isSystem = 5;</code>
       */
      public boolean getIsSystem() {
        return isSystem_;
      }
      /**
       * <code>required bool isSystem = 5;</code>
       */
      public Builder setIsSystem(boolean value) {
        bitField0_ |= 0x00000010;
        isSystem_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool isSystem = 5;</code>
       */
      public Builder clearIsSystem() {
        bitField0_ = (bitField0_ & ~0x00000010);
        isSystem_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:AppInfo)
    }

    static {
      defaultInstance = new AppInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:AppInfo)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AppListResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_AppListResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AppInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_AppInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025AppListResponse.proto\"J\n\017AppListRespon" +
      "se\022\021\n\tmessageId\030\001 \002(\t\022\014\n\004code\030\002 \002(\005\022\026\n\004l" +
      "ist\030\003 \003(\0132\010.AppInfo\"k\n\007AppInfo\022\023\n\013packag" +
      "eName\030\001 \002(\t\022\017\n\007appName\030\002 \002(\t\022\023\n\013versionC" +
      "ode\030\003 \002(\005\022\023\n\013versionName\030\004 \002(\t\022\020\n\010isSyst" +
      "em\030\005 \002(\010B1\n\031com.netty.client.innermsgB\024A" +
      "ppListResponseProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_AppListResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AppListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_AppListResponse_descriptor,
        new java.lang.String[] { "MessageId", "Code", "List", });
    internal_static_AppInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_AppInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_AppInfo_descriptor,
        new java.lang.String[] { "PackageName", "AppName", "VersionCode", "VersionName", "IsSystem", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
