// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: KeyResponse.proto

package com.tencent.tvmanager.netty.innermsg;

public final class KeyResponseProto {
  private KeyResponseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface KeyResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:KeyResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string messageId = 1;</code>
     *
     * <pre>
     *消息id
     * </pre>
     */
    boolean hasMessageId();
    /**
     * <code>required string messageId = 1;</code>
     *
     * <pre>
     *消息id
     * </pre>
     */
    java.lang.String getMessageId();
    /**
     * <code>required string messageId = 1;</code>
     *
     * <pre>
     *消息id
     * </pre>
     */
    com.google.protobuf.ByteString
        getMessageIdBytes();

    /**
     * <code>required int32 code = 2;</code>
     *
     * <pre>
     *返回code
     * </pre>
     */
    boolean hasCode();
    /**
     * <code>required int32 code = 2;</code>
     *
     * <pre>
     *返回code
     * </pre>
     */
    int getCode();

    /**
     * <code>optional int32 versionCode = 3;</code>
     *
     * <pre>
     *APP版本code
     * </pre>
     */
    boolean hasVersionCode();
    /**
     * <code>optional int32 versionCode = 3;</code>
     *
     * <pre>
     *APP版本code
     * </pre>
     */
    int getVersionCode();

    /**
     * <code>optional string versionName = 4;</code>
     *
     * <pre>
     *APP版本name
     * </pre>
     */
    boolean hasVersionName();
    /**
     * <code>optional string versionName = 4;</code>
     *
     * <pre>
     *APP版本name
     * </pre>
     */
    java.lang.String getVersionName();
    /**
     * <code>optional string versionName = 4;</code>
     *
     * <pre>
     *APP版本name
     * </pre>
     */
    com.google.protobuf.ByteString
        getVersionNameBytes();

    /**
     * <code>required int32 protocol = 5;</code>
     *
     * <pre>
     *协议版本
     * </pre>
     */
    boolean hasProtocol();
    /**
     * <code>required int32 protocol = 5;</code>
     *
     * <pre>
     *协议版本
     * </pre>
     */
    int getProtocol();
  }
  /**
   * Protobuf type {@code KeyResponse}
   */
  public static final class KeyResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:KeyResponse)
      KeyResponseOrBuilder {
    // Use KeyResponse.newBuilder() to construct.
    private KeyResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private KeyResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final KeyResponse defaultInstance;
    public static KeyResponse getDefaultInstance() {
      return defaultInstance;
    }

    public KeyResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private KeyResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              messageId_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              code_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              versionCode_ = input.readInt32();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              versionName_ = bs;
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              protocol_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tencent.tvmanager.netty.innermsg.KeyResponseProto.internal_static_KeyResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tencent.tvmanager.netty.innermsg.KeyResponseProto.internal_static_KeyResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tencent.tvmanager.netty.innermsg.KeyResponseProto.KeyResponse.class, com.tencent.tvmanager.netty.innermsg.KeyResponseProto.KeyResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<KeyResponse> PARSER =
        new com.google.protobuf.AbstractParser<KeyResponse>() {
      public KeyResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new KeyResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<KeyResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int MESSAGEID_FIELD_NUMBER = 1;
    private java.lang.Object messageId_;
    /**
     * <code>required string messageId = 1;</code>
     *
     * <pre>
     *消息id
     * </pre>
     */
    public boolean hasMessageId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string messageId = 1;</code>
     *
     * <pre>
     *消息id
     * </pre>
     */
    public java.lang.String getMessageId() {
      java.lang.Object ref = messageId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          messageId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string messageId = 1;</code>
     *
     * <pre>
     *消息id
     * </pre>
     */
    public com.google.protobuf.ByteString
        getMessageIdBytes() {
      java.lang.Object ref = messageId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CODE_FIELD_NUMBER = 2;
    private int code_;
    /**
     * <code>required int32 code = 2;</code>
     *
     * <pre>
     *返回code
     * </pre>
     */
    public boolean hasCode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 code = 2;</code>
     *
     * <pre>
     *返回code
     * </pre>
     */
    public int getCode() {
      return code_;
    }

    public static final int VERSIONCODE_FIELD_NUMBER = 3;
    private int versionCode_;
    /**
     * <code>optional int32 versionCode = 3;</code>
     *
     * <pre>
     *APP版本code
     * </pre>
     */
    public boolean hasVersionCode() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 versionCode = 3;</code>
     *
     * <pre>
     *APP版本code
     * </pre>
     */
    public int getVersionCode() {
      return versionCode_;
    }

    public static final int VERSIONNAME_FIELD_NUMBER = 4;
    private java.lang.Object versionName_;
    /**
     * <code>optional string versionName = 4;</code>
     *
     * <pre>
     *APP版本name
     * </pre>
     */
    public boolean hasVersionName() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string versionName = 4;</code>
     *
     * <pre>
     *APP版本name
     * </pre>
     */
    public java.lang.String getVersionName() {
      java.lang.Object ref = versionName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          versionName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string versionName = 4;</code>
     *
     * <pre>
     *APP版本name
     * </pre>
     */
    public com.google.protobuf.ByteString
        getVersionNameBytes() {
      java.lang.Object ref = versionName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        versionName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PROTOCOL_FIELD_NUMBER = 5;
    private int protocol_;
    /**
     * <code>required int32 protocol = 5;</code>
     *
     * <pre>
     *协议版本
     * </pre>
     */
    public boolean hasProtocol() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 protocol = 5;</code>
     *
     * <pre>
     *协议版本
     * </pre>
     */
    public int getProtocol() {
      return protocol_;
    }

    private void initFields() {
      messageId_ = "";
      code_ = 0;
      versionCode_ = 0;
      versionName_ = "";
      protocol_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasMessageId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasProtocol()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getMessageIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, code_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, versionCode_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getVersionNameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, protocol_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getMessageIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, code_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, versionCode_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getVersionNameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, protocol_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.tencent.tvmanager.netty.innermsg.KeyResponseProto.KeyResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.tvmanager.netty.innermsg.KeyResponseProto.KeyResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.tvmanager.netty.innermsg.KeyResponseProto.KeyResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.tvmanager.netty.innermsg.KeyResponseProto.KeyResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.tvmanager.netty.innermsg.KeyResponseProto.KeyResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.tencent.tvmanager.netty.innermsg.KeyResponseProto.KeyResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.tencent.tvmanager.netty.innermsg.KeyResponseProto.KeyResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.tencent.tvmanager.netty.innermsg.KeyResponseProto.KeyResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.tencent.tvmanager.netty.innermsg.KeyResponseProto.KeyResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.tencent.tvmanager.netty.innermsg.KeyResponseProto.KeyResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.tencent.tvmanager.netty.innermsg.KeyResponseProto.KeyResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code KeyResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:KeyResponse)
        com.tencent.tvmanager.netty.innermsg.KeyResponseProto.KeyResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tencent.tvmanager.netty.innermsg.KeyResponseProto.internal_static_KeyResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tencent.tvmanager.netty.innermsg.KeyResponseProto.internal_static_KeyResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tencent.tvmanager.netty.innermsg.KeyResponseProto.KeyResponse.class, com.tencent.tvmanager.netty.innermsg.KeyResponseProto.KeyResponse.Builder.class);
      }

      // Construct using com.tencent.tvmanager.netty.innermsg.KeyResponseProto.KeyResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        messageId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        code_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        versionCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        versionName_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        protocol_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tencent.tvmanager.netty.innermsg.KeyResponseProto.internal_static_KeyResponse_descriptor;
      }

      public com.tencent.tvmanager.netty.innermsg.KeyResponseProto.KeyResponse getDefaultInstanceForType() {
        return com.tencent.tvmanager.netty.innermsg.KeyResponseProto.KeyResponse.getDefaultInstance();
      }

      public com.tencent.tvmanager.netty.innermsg.KeyResponseProto.KeyResponse build() {
        com.tencent.tvmanager.netty.innermsg.KeyResponseProto.KeyResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.tencent.tvmanager.netty.innermsg.KeyResponseProto.KeyResponse buildPartial() {
        com.tencent.tvmanager.netty.innermsg.KeyResponseProto.KeyResponse result = new com.tencent.tvmanager.netty.innermsg.KeyResponseProto.KeyResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.messageId_ = messageId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.code_ = code_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.versionCode_ = versionCode_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.versionName_ = versionName_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.protocol_ = protocol_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tencent.tvmanager.netty.innermsg.KeyResponseProto.KeyResponse) {
          return mergeFrom((com.tencent.tvmanager.netty.innermsg.KeyResponseProto.KeyResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tencent.tvmanager.netty.innermsg.KeyResponseProto.KeyResponse other) {
        if (other == com.tencent.tvmanager.netty.innermsg.KeyResponseProto.KeyResponse.getDefaultInstance()) return this;
        if (other.hasMessageId()) {
          bitField0_ |= 0x00000001;
          messageId_ = other.messageId_;
          onChanged();
        }
        if (other.hasCode()) {
          setCode(other.getCode());
        }
        if (other.hasVersionCode()) {
          setVersionCode(other.getVersionCode());
        }
        if (other.hasVersionName()) {
          bitField0_ |= 0x00000008;
          versionName_ = other.versionName_;
          onChanged();
        }
        if (other.hasProtocol()) {
          setProtocol(other.getProtocol());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMessageId()) {
          
          return false;
        }
        if (!hasCode()) {
          
          return false;
        }
        if (!hasProtocol()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tencent.tvmanager.netty.innermsg.KeyResponseProto.KeyResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tencent.tvmanager.netty.innermsg.KeyResponseProto.KeyResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object messageId_ = "";
      /**
       * <code>required string messageId = 1;</code>
       *
       * <pre>
       *消息id
       * </pre>
       */
      public boolean hasMessageId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string messageId = 1;</code>
       *
       * <pre>
       *消息id
       * </pre>
       */
      public java.lang.String getMessageId() {
        java.lang.Object ref = messageId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            messageId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string messageId = 1;</code>
       *
       * <pre>
       *消息id
       * </pre>
       */
      public com.google.protobuf.ByteString
          getMessageIdBytes() {
        java.lang.Object ref = messageId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          messageId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string messageId = 1;</code>
       *
       * <pre>
       *消息id
       * </pre>
       */
      public Builder setMessageId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        messageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string messageId = 1;</code>
       *
       * <pre>
       *消息id
       * </pre>
       */
      public Builder clearMessageId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        messageId_ = getDefaultInstance().getMessageId();
        onChanged();
        return this;
      }
      /**
       * <code>required string messageId = 1;</code>
       *
       * <pre>
       *消息id
       * </pre>
       */
      public Builder setMessageIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        messageId_ = value;
        onChanged();
        return this;
      }

      private int code_ ;
      /**
       * <code>required int32 code = 2;</code>
       *
       * <pre>
       *返回code
       * </pre>
       */
      public boolean hasCode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 code = 2;</code>
       *
       * <pre>
       *返回code
       * </pre>
       */
      public int getCode() {
        return code_;
      }
      /**
       * <code>required int32 code = 2;</code>
       *
       * <pre>
       *返回code
       * </pre>
       */
      public Builder setCode(int value) {
        bitField0_ |= 0x00000002;
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 code = 2;</code>
       *
       * <pre>
       *返回code
       * </pre>
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        code_ = 0;
        onChanged();
        return this;
      }

      private int versionCode_ ;
      /**
       * <code>optional int32 versionCode = 3;</code>
       *
       * <pre>
       *APP版本code
       * </pre>
       */
      public boolean hasVersionCode() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 versionCode = 3;</code>
       *
       * <pre>
       *APP版本code
       * </pre>
       */
      public int getVersionCode() {
        return versionCode_;
      }
      /**
       * <code>optional int32 versionCode = 3;</code>
       *
       * <pre>
       *APP版本code
       * </pre>
       */
      public Builder setVersionCode(int value) {
        bitField0_ |= 0x00000004;
        versionCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 versionCode = 3;</code>
       *
       * <pre>
       *APP版本code
       * </pre>
       */
      public Builder clearVersionCode() {
        bitField0_ = (bitField0_ & ~0x00000004);
        versionCode_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object versionName_ = "";
      /**
       * <code>optional string versionName = 4;</code>
       *
       * <pre>
       *APP版本name
       * </pre>
       */
      public boolean hasVersionName() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string versionName = 4;</code>
       *
       * <pre>
       *APP版本name
       * </pre>
       */
      public java.lang.String getVersionName() {
        java.lang.Object ref = versionName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            versionName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string versionName = 4;</code>
       *
       * <pre>
       *APP版本name
       * </pre>
       */
      public com.google.protobuf.ByteString
          getVersionNameBytes() {
        java.lang.Object ref = versionName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          versionName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string versionName = 4;</code>
       *
       * <pre>
       *APP版本name
       * </pre>
       */
      public Builder setVersionName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        versionName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string versionName = 4;</code>
       *
       * <pre>
       *APP版本name
       * </pre>
       */
      public Builder clearVersionName() {
        bitField0_ = (bitField0_ & ~0x00000008);
        versionName_ = getDefaultInstance().getVersionName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string versionName = 4;</code>
       *
       * <pre>
       *APP版本name
       * </pre>
       */
      public Builder setVersionNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        versionName_ = value;
        onChanged();
        return this;
      }

      private int protocol_ ;
      /**
       * <code>required int32 protocol = 5;</code>
       *
       * <pre>
       *协议版本
       * </pre>
       */
      public boolean hasProtocol() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int32 protocol = 5;</code>
       *
       * <pre>
       *协议版本
       * </pre>
       */
      public int getProtocol() {
        return protocol_;
      }
      /**
       * <code>required int32 protocol = 5;</code>
       *
       * <pre>
       *协议版本
       * </pre>
       */
      public Builder setProtocol(int value) {
        bitField0_ |= 0x00000010;
        protocol_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 protocol = 5;</code>
       *
       * <pre>
       *协议版本
       * </pre>
       */
      public Builder clearProtocol() {
        bitField0_ = (bitField0_ & ~0x00000010);
        protocol_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:KeyResponse)
    }

    static {
      defaultInstance = new KeyResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:KeyResponse)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_KeyResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_KeyResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021KeyResponse.proto\"j\n\013KeyResponse\022\021\n\tme" +
      "ssageId\030\001 \002(\t\022\014\n\004code\030\002 \002(\005\022\023\n\013versionCo" +
      "de\030\003 \001(\005\022\023\n\013versionName\030\004 \001(\t\022\020\n\010protoco" +
      "l\030\005 \002(\005B8\n$com.tencent.tvmanager.netty.i" +
      "nnermsgB\020KeyResponseProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_KeyResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_KeyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_KeyResponse_descriptor,
        new java.lang.String[] { "MessageId", "Code", "VersionCode", "VersionName", "Protocol", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
