// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: KeyResponse.proto

package com.tencent.tvmanager.netty.msg;

public final class KeyResponseProto {
  private KeyResponseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface KeyResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:KeyResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>required string messageId = 1;</code>
     */
    boolean hasMessageId();
    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>required string messageId = 1;</code>
     */
    java.lang.String getMessageId();
    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>required string messageId = 1;</code>
     */
    com.google.protobuf.ByteString
        getMessageIdBytes();

    /**
     * <pre>
     *返回code
     * </pre>
     *
     * <code>required int32 code = 2;</code>
     */
    boolean hasCode();
    /**
     * <pre>
     *返回code
     * </pre>
     *
     * <code>required int32 code = 2;</code>
     */
    int getCode();

    /**
     * <code>optional int32 versionCode = 3;</code>
     */
    boolean hasVersionCode();
    /**
     * <code>optional int32 versionCode = 3;</code>
     */
    int getVersionCode();

    /**
     * <code>optional string versionName = 4;</code>
     */
    boolean hasVersionName();
    /**
     * <code>optional string versionName = 4;</code>
     */
    java.lang.String getVersionName();
    /**
     * <code>optional string versionName = 4;</code>
     */
    com.google.protobuf.ByteString
        getVersionNameBytes();
  }
  /**
   * Protobuf type {@code KeyResponse}
   */
  public  static final class KeyResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:KeyResponse)
      KeyResponseOrBuilder {
    // Use KeyResponse.newBuilder() to construct.
    private KeyResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private KeyResponse() {
      messageId_ = "";
      code_ = 0;
      versionCode_ = 0;
      versionName_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private KeyResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              messageId_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              code_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              versionCode_ = input.readInt32();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              versionName_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tencent.tvmanager.netty.msg.KeyResponseProto.internal_static_KeyResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tencent.tvmanager.netty.msg.KeyResponseProto.internal_static_KeyResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tencent.tvmanager.netty.msg.KeyResponseProto.KeyResponse.class, com.tencent.tvmanager.netty.msg.KeyResponseProto.KeyResponse.Builder.class);
    }

    private int bitField0_;
    public static final int MESSAGEID_FIELD_NUMBER = 1;
    private volatile java.lang.Object messageId_;
    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>required string messageId = 1;</code>
     */
    public boolean hasMessageId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>required string messageId = 1;</code>
     */
    public java.lang.String getMessageId() {
      java.lang.Object ref = messageId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          messageId_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>required string messageId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMessageIdBytes() {
      java.lang.Object ref = messageId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CODE_FIELD_NUMBER = 2;
    private int code_;
    /**
     * <pre>
     *返回code
     * </pre>
     *
     * <code>required int32 code = 2;</code>
     */
    public boolean hasCode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     *返回code
     * </pre>
     *
     * <code>required int32 code = 2;</code>
     */
    public int getCode() {
      return code_;
    }

    public static final int VERSIONCODE_FIELD_NUMBER = 3;
    private int versionCode_;
    /**
     * <code>optional int32 versionCode = 3;</code>
     */
    public boolean hasVersionCode() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 versionCode = 3;</code>
     */
    public int getVersionCode() {
      return versionCode_;
    }

    public static final int VERSIONNAME_FIELD_NUMBER = 4;
    private volatile java.lang.Object versionName_;
    /**
     * <code>optional string versionName = 4;</code>
     */
    public boolean hasVersionName() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string versionName = 4;</code>
     */
    public java.lang.String getVersionName() {
      java.lang.Object ref = versionName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          versionName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string versionName = 4;</code>
     */
    public com.google.protobuf.ByteString
        getVersionNameBytes() {
      java.lang.Object ref = versionName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        versionName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasMessageId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, messageId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, code_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, versionCode_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, versionName_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, messageId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, code_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, versionCode_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, versionName_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tencent.tvmanager.netty.msg.KeyResponseProto.KeyResponse)) {
        return super.equals(obj);
      }
      com.tencent.tvmanager.netty.msg.KeyResponseProto.KeyResponse other = (com.tencent.tvmanager.netty.msg.KeyResponseProto.KeyResponse) obj;

      boolean result = true;
      result = result && (hasMessageId() == other.hasMessageId());
      if (hasMessageId()) {
        result = result && getMessageId()
            .equals(other.getMessageId());
      }
      result = result && (hasCode() == other.hasCode());
      if (hasCode()) {
        result = result && (getCode()
            == other.getCode());
      }
      result = result && (hasVersionCode() == other.hasVersionCode());
      if (hasVersionCode()) {
        result = result && (getVersionCode()
            == other.getVersionCode());
      }
      result = result && (hasVersionName() == other.hasVersionName());
      if (hasVersionName()) {
        result = result && getVersionName()
            .equals(other.getVersionName());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasMessageId()) {
        hash = (37 * hash) + MESSAGEID_FIELD_NUMBER;
        hash = (53 * hash) + getMessageId().hashCode();
      }
      if (hasCode()) {
        hash = (37 * hash) + CODE_FIELD_NUMBER;
        hash = (53 * hash) + getCode();
      }
      if (hasVersionCode()) {
        hash = (37 * hash) + VERSIONCODE_FIELD_NUMBER;
        hash = (53 * hash) + getVersionCode();
      }
      if (hasVersionName()) {
        hash = (37 * hash) + VERSIONNAME_FIELD_NUMBER;
        hash = (53 * hash) + getVersionName().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tencent.tvmanager.netty.msg.KeyResponseProto.KeyResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.tvmanager.netty.msg.KeyResponseProto.KeyResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.tvmanager.netty.msg.KeyResponseProto.KeyResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.tvmanager.netty.msg.KeyResponseProto.KeyResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.tvmanager.netty.msg.KeyResponseProto.KeyResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tencent.tvmanager.netty.msg.KeyResponseProto.KeyResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tencent.tvmanager.netty.msg.KeyResponseProto.KeyResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tencent.tvmanager.netty.msg.KeyResponseProto.KeyResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tencent.tvmanager.netty.msg.KeyResponseProto.KeyResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tencent.tvmanager.netty.msg.KeyResponseProto.KeyResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tencent.tvmanager.netty.msg.KeyResponseProto.KeyResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code KeyResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:KeyResponse)
        com.tencent.tvmanager.netty.msg.KeyResponseProto.KeyResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tencent.tvmanager.netty.msg.KeyResponseProto.internal_static_KeyResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tencent.tvmanager.netty.msg.KeyResponseProto.internal_static_KeyResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tencent.tvmanager.netty.msg.KeyResponseProto.KeyResponse.class, com.tencent.tvmanager.netty.msg.KeyResponseProto.KeyResponse.Builder.class);
      }

      // Construct using com.tencent.tvmanager.netty.msg.KeyResponseProto.KeyResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        messageId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        code_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        versionCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        versionName_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tencent.tvmanager.netty.msg.KeyResponseProto.internal_static_KeyResponse_descriptor;
      }

      public com.tencent.tvmanager.netty.msg.KeyResponseProto.KeyResponse getDefaultInstanceForType() {
        return com.tencent.tvmanager.netty.msg.KeyResponseProto.KeyResponse.getDefaultInstance();
      }

      public com.tencent.tvmanager.netty.msg.KeyResponseProto.KeyResponse build() {
        com.tencent.tvmanager.netty.msg.KeyResponseProto.KeyResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.tencent.tvmanager.netty.msg.KeyResponseProto.KeyResponse buildPartial() {
        com.tencent.tvmanager.netty.msg.KeyResponseProto.KeyResponse result = new com.tencent.tvmanager.netty.msg.KeyResponseProto.KeyResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.messageId_ = messageId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.code_ = code_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.versionCode_ = versionCode_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.versionName_ = versionName_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tencent.tvmanager.netty.msg.KeyResponseProto.KeyResponse) {
          return mergeFrom((com.tencent.tvmanager.netty.msg.KeyResponseProto.KeyResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tencent.tvmanager.netty.msg.KeyResponseProto.KeyResponse other) {
        if (other == com.tencent.tvmanager.netty.msg.KeyResponseProto.KeyResponse.getDefaultInstance()) return this;
        if (other.hasMessageId()) {
          bitField0_ |= 0x00000001;
          messageId_ = other.messageId_;
          onChanged();
        }
        if (other.hasCode()) {
          setCode(other.getCode());
        }
        if (other.hasVersionCode()) {
          setVersionCode(other.getVersionCode());
        }
        if (other.hasVersionName()) {
          bitField0_ |= 0x00000008;
          versionName_ = other.versionName_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMessageId()) {
          return false;
        }
        if (!hasCode()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tencent.tvmanager.netty.msg.KeyResponseProto.KeyResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tencent.tvmanager.netty.msg.KeyResponseProto.KeyResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object messageId_ = "";
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>required string messageId = 1;</code>
       */
      public boolean hasMessageId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>required string messageId = 1;</code>
       */
      public java.lang.String getMessageId() {
        java.lang.Object ref = messageId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            messageId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>required string messageId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMessageIdBytes() {
        java.lang.Object ref = messageId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          messageId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>required string messageId = 1;</code>
       */
      public Builder setMessageId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        messageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>required string messageId = 1;</code>
       */
      public Builder clearMessageId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        messageId_ = getDefaultInstance().getMessageId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>required string messageId = 1;</code>
       */
      public Builder setMessageIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        messageId_ = value;
        onChanged();
        return this;
      }

      private int code_ ;
      /**
       * <pre>
       *返回code
       * </pre>
       *
       * <code>required int32 code = 2;</code>
       */
      public boolean hasCode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       *返回code
       * </pre>
       *
       * <code>required int32 code = 2;</code>
       */
      public int getCode() {
        return code_;
      }
      /**
       * <pre>
       *返回code
       * </pre>
       *
       * <code>required int32 code = 2;</code>
       */
      public Builder setCode(int value) {
        bitField0_ |= 0x00000002;
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *返回code
       * </pre>
       *
       * <code>required int32 code = 2;</code>
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        code_ = 0;
        onChanged();
        return this;
      }

      private int versionCode_ ;
      /**
       * <code>optional int32 versionCode = 3;</code>
       */
      public boolean hasVersionCode() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 versionCode = 3;</code>
       */
      public int getVersionCode() {
        return versionCode_;
      }
      /**
       * <code>optional int32 versionCode = 3;</code>
       */
      public Builder setVersionCode(int value) {
        bitField0_ |= 0x00000004;
        versionCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 versionCode = 3;</code>
       */
      public Builder clearVersionCode() {
        bitField0_ = (bitField0_ & ~0x00000004);
        versionCode_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object versionName_ = "";
      /**
       * <code>optional string versionName = 4;</code>
       */
      public boolean hasVersionName() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string versionName = 4;</code>
       */
      public java.lang.String getVersionName() {
        java.lang.Object ref = versionName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            versionName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string versionName = 4;</code>
       */
      public com.google.protobuf.ByteString
          getVersionNameBytes() {
        java.lang.Object ref = versionName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          versionName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string versionName = 4;</code>
       */
      public Builder setVersionName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        versionName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string versionName = 4;</code>
       */
      public Builder clearVersionName() {
        bitField0_ = (bitField0_ & ~0x00000008);
        versionName_ = getDefaultInstance().getVersionName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string versionName = 4;</code>
       */
      public Builder setVersionNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        versionName_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:KeyResponse)
    }

    // @@protoc_insertion_point(class_scope:KeyResponse)
    private static final com.tencent.tvmanager.netty.msg.KeyResponseProto.KeyResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tencent.tvmanager.netty.msg.KeyResponseProto.KeyResponse();
    }

    public static com.tencent.tvmanager.netty.msg.KeyResponseProto.KeyResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<KeyResponse>
        PARSER = new com.google.protobuf.AbstractParser<KeyResponse>() {
      public KeyResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new KeyResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<KeyResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<KeyResponse> getParserForType() {
      return PARSER;
    }

    public com.tencent.tvmanager.netty.msg.KeyResponseProto.KeyResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_KeyResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_KeyResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021KeyResponse.proto\"X\n\013KeyResponse\022\021\n\tme" +
      "ssageId\030\001 \002(\t\022\014\n\004code\030\002 \002(\005\022\023\n\013versionCo" +
      "de\030\003 \001(\005\022\023\n\013versionName\030\004 \001(\tB3\n\037com.ten" +
      "cent.tvmanager.netty.msgB\020KeyResponsePro" +
      "to"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_KeyResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_KeyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_KeyResponse_descriptor,
        new java.lang.String[] { "MessageId", "Code", "VersionCode", "VersionName", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
